# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='FixedIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.Account')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.Agency')),
            ],
        ),
    ]
