# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
            ],
            options={
                'verbose_name_plural': '机构',
                'verbose_name': '投资种类',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name'], 'verbose_name': '户头', 'verbose_name_plural': '户头'},
        ),
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['name'], 'verbose_name': '机构', 'verbose_name_plural': '机构'},
        ),
        migrations.AlterModelOptions(
            name='fixedincome',
            options={'verbose_name': '固定收益类', 'verbose_name_plural': '固定收益类'},
        ),
        migrations.AddField(
            model_name='fixedincome',
            name='spend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='投入'),
        ),
        migrations.AlterField(
            model_name='fixedincome',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.Account', verbose_name='户头'),
        ),
        migrations.AlterField(
            model_name='fixedincome',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.Agency', verbose_name='机构'),
        ),
    ]
