# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_auto_20160922_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investtype',
            options={'ordering': ['name'], 'verbose_name': '投资类别', 'verbose_name_plural': '机构'},
        ),
        migrations.AddField(
            model_name='fixedincome',
            name='investtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.InvestType', verbose_name='投资类别'),
        ),
        migrations.AlterField(
            model_name='fixedincome',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.Account', verbose_name='户头'),
        ),
        migrations.AlterField(
            model_name='fixedincome',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.Agency', verbose_name='机构'),
        ),
    ]
