# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_auto_20160922_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investtype',
            options={'ordering': ['name'], 'verbose_name': '投资类别', 'verbose_name_plural': '投资类别'},
        ),
        migrations.AddField(
            model_name='investtype',
            name='subname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='子类名'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='fixedincome',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='fixedincome',
            name='spend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='投入'),
        ),
        migrations.AlterField(
            model_name='investtype',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='类名'),
        ),
    ]
