# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0005_auto_20160922_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investtype',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='说明'),
        ),
    ]
