# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0006_auto_20160922_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investtype',
            name='liquidity',
            field=models.CharField(blank=True, choices=[('1', '高'), ('2', '中'), ('3', '低')], max_length=1, null=True, verbose_name='流动性'),
        ),
    ]
