# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0007_auto_20160922_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedincome',
            name='buydate',
            field=models.DateField(auto_now=True, null=True, verbose_name='购入时间'),
        ),
        migrations.AddField(
            model_name='fixedincome',
            name='maturity',
            field=models.DateField(auto_now=True, null=True, verbose_name='购入时间'),
        ),
    ]
