# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0008_auto_20160922_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedincome',
            name='maturity',
            field=models.DateField(auto_now=True, null=True, verbose_name='到期时间'),
        ),
    ]
