# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0012_auto_20160922_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intrest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='类名')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name_plural': '利息类型',
                'verbose_name': '利息类型',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='fixedincome',
            name='interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.Intrest', verbose_name='利息类型'),
        ),
    ]
