# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0013_auto_20160922_0946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intrest',
            new_name='IntrestType',
        ),
        migrations.RenameField(
            model_name='fixedincome',
            old_name='interest',
            new_name='intrestype',
        ),
    ]
