# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0017_auto_20160922_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedincome',
            name='spend',
            field=models.FloatField(blank=True, null=True, verbose_name='投入'),
        ),
    ]
