# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0018_auto_20160922_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedincome',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='已完成'),
        ),
    ]
