# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0019_fixedincome_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedIncomeCashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happenddate', models.DateField(verbose_name='日期')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='金额')),
                ('relatefixedincome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.FixedIncome', verbose_name='相关固定收益类')),
            ],
            options={
                'verbose_name': '定收益类现金流',
                'ordering': ['happenddate'],
                'verbose_name_plural': '定收益类现金流',
            },
        ),
    ]
