# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0021_auto_20160930_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFundInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='股票名称')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='股票代码')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='股票价格')),
                ('type', models.CharField(blank=True, choices=[('1', '股票'), ('2', '基金')], max_length=1, null=True, verbose_name='类型')),
            ],
            options={
                'ordering': ['code'],
                'verbose_name_plural': '股票基金信息',
                'verbose_name': '股票基金信息',
            },
        ),
    ]
