# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0022_stockfundinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfundinfo',
            name='type',
            field=models.CharField(blank=True, choices=[('1', '股票'), ('2', '基金'), ('3', '自定义')], max_length=1, null=True, verbose_name='类型'),
        ),
    ]
