# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0023_auto_20161009_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockFundInfo',
            new_name='EquityInfo',
        ),
        migrations.AlterModelOptions(
            name='equityinfo',
            options={'ordering': ['code'], 'verbose_name': '权益类信息', 'verbose_name_plural': '权益类信息'},
        ),
    ]
