# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0024_auto_20161014_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='EquityInfo',
            new_name='Equity',
        ),
        migrations.AddField(
            model_name='equityreg',
            name='Equity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.Equity', verbose_name='权益类信息'),
        ),
        migrations.AddField(
            model_name='equityreg',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.Agency', verbose_name='机构'),
        ),
    ]
