# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0025_auto_20161014_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['Name'], 'verbose_name': '户头', 'verbose_name_plural': '户头'},
        ),
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['Name'], 'verbose_name': '机构', 'verbose_name_plural': '机构'},
        ),
        migrations.AlterModelOptions(
            name='equity',
            options={'ordering': ['Type', 'Code'], 'verbose_name': '权益类信息', 'verbose_name_plural': '权益类信息'},
        ),
        migrations.AlterModelOptions(
            name='equityreg',
            options={'ordering': ['TradeDate', 'Account', 'Agency'], 'verbose_name': '权益类登记', 'verbose_name_plural': '权益类登记'},
        ),
        migrations.AlterModelOptions(
            name='fixedincome',
            options={'ordering': ['Buydate', 'Account', 'Agency'], 'verbose_name': '固定收益类', 'verbose_name_plural': '固定收益类'},
        ),
        migrations.AlterModelOptions(
            name='fixedincomecashflow',
            options={'ordering': ['HappendDate'], 'verbose_name': '固定收益类现金流', 'verbose_name_plural': '固定收益类现金流'},
        ),
        migrations.AlterModelOptions(
            name='intresttype',
            options={'ordering': ['Name'], 'verbose_name': '利息类型', 'verbose_name_plural': '利息类型'},
        ),
        migrations.AlterModelOptions(
            name='investtype',
            options={'ordering': ['Name', 'SubName'], 'verbose_name': '投资类别', 'verbose_name_plural': '投资类别'},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='comment',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='agency',
            old_name='comment',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='agency',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='equity',
            old_name='code',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='equity',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='equity',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='equity',
            old_name='type',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='equityreg',
            old_name='agency',
            new_name='Agency',
        ),
        migrations.RenameField(
            model_name='fixedincome',
            old_name='account',
            new_name='Account',
        ),
        migrations.RenameField(
            model_name='fixedincome',
            old_name='agency',
            new_name='Agency',
        ),
        migrations.RenameField(
            model_name='fixedincome',
            old_name='annualizedyield',
            new_name='AnnualizedYield',
        ),
        migrations.RenameField(
            model_name='fixedincome',
            old_name='buydate',
            new_name='Buydate',
        ),
        migrations.RenameField(
            model_name='fixedincome',
            old_name='comment',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='fixedincome',
            old_name='completed',
            new_name='Completed',
        ),
        migrations.RenameField(
            model_name='fixedincome',
            old_name='discount',
            new_name='Discount',
        ),
        migrations.RenameField(
            model_name='fixedincome',
            old_name='intrestype',
            new_name='IntresType',
        ),
        migrations.RenameField(
            model_name='fixedincome',
            old_name='investtype',
            new_name='Investtype',
        ),
        migrations.RenameField(
            model_name='fixedincome',
            old_name='maturity',
            new_name='Maturity',
        ),
        migrations.RenameField(
            model_name='fixedincome',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='fixedincome',
            old_name='spend',
            new_name='Spend',
        ),
        migrations.RenameField(
            model_name='fixedincomecashflow',
            old_name='amount',
            new_name='Amount',
        ),
        migrations.RenameField(
            model_name='fixedincomecashflow',
            old_name='happenddate',
            new_name='HappendDate',
        ),
        migrations.RenameField(
            model_name='fixedincomecashflow',
            old_name='relatefixedincome',
            new_name='RelateFixedIncome',
        ),
        migrations.RenameField(
            model_name='intresttype',
            old_name='comment',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='intresttype',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='investtype',
            old_name='comment',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='investtype',
            old_name='liquidity',
            new_name='Liquidity',
        ),
        migrations.RenameField(
            model_name='investtype',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='investtype',
            old_name='risk',
            new_name='Risk',
        ),
        migrations.RenameField(
            model_name='investtype',
            old_name='subname',
            new_name='SubName',
        ),
        migrations.AddField(
            model_name='equityreg',
            name='Account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.Account', verbose_name='户头'),
        ),
        migrations.AddField(
            model_name='equityreg',
            name='Amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='成交金额'),
        ),
        migrations.AddField(
            model_name='equityreg',
            name='Comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='说明'),
        ),
        migrations.AddField(
            model_name='equityreg',
            name='InvestType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.InvestType', verbose_name='投资类别'),
        ),
        migrations.AddField(
            model_name='equityreg',
            name='Price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='成交单价'),
        ),
        migrations.AddField(
            model_name='equityreg',
            name='Quantity',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='成交数量'),
        ),
        migrations.AddField(
            model_name='equityreg',
            name='TradeDate',
            field=models.DateField(null=True, verbose_name='成交日期'),
        ),
    ]
