# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0027_auto_20161017_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchimport',
            name='UploadTime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='上传时间'),
        ),
    ]
