# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0028_auto_20161017_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchimport',
            old_name='Name',
            new_name='ModelName',
        ),
    ]
