# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0029_auto_20161022_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['Type', 'Name'], 'verbose_name': '机构', 'verbose_name_plural': '机构'},
        ),
        migrations.AddField(
            model_name='agency',
            name='Type',
            field=models.CharField(blank=True, choices=[('1', '银行'), ('2', '证券公司'), ('3', '理财平台'), ('3', 'p2p平台'), ('4', '基金公司')], max_length=1, null=True, verbose_name='机构类型'),
        ),
        migrations.AlterField(
            model_name='batchimport',
            name='ModelName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='模型名称'),
        ),
        migrations.AlterField(
            model_name='batchimport',
            name='UploadFile',
            field=models.FileField(upload_to='./upload/%Y-%m-%d/', verbose_name='上传文件'),
        ),
    ]
