# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0030_auto_20161028_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='Type',
            field=models.CharField(blank=True, choices=[('1', '上海'), ('2', '深圳'), ('3', '基金'), ('4', '自定义')], max_length=1, null=True, verbose_name='类型'),
        ),
    ]
