# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0031_auto_20161028_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='Type',
            field=models.CharField(blank=True, choices=[('1', '银行'), ('2', '证券公司'), ('3', '理财平台'), ('4', 'p2p平台'), ('5', '基金公司')], max_length=1, null=True, verbose_name='机构类型'),
        ),
    ]
