# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0032_auto_20161029_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True, verbose_name='类型名称')),
            ],
            options={
                'verbose_name_plural': '机构类型',
                'ordering': ['Name'],
                'verbose_name': '机构类型',
            },
        ),
        migrations.AlterField(
            model_name='agency',
            name='Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.AgencyType', verbose_name='机构类型'),
        ),
    ]
