# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0033_auto_20161030_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='KeyName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主键名称'),
        ),
        migrations.AddField(
            model_name='agency',
            name='KeyName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主键名称'),
        ),
        migrations.AddField(
            model_name='agencytype',
            name='KeyName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主键名称'),
        ),
        migrations.AddField(
            model_name='batchimport',
            name='KeyName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主键名称'),
        ),
        migrations.AddField(
            model_name='equity',
            name='KeyName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主键名称'),
        ),
        migrations.AddField(
            model_name='equityreg',
            name='KeyName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主键名称'),
        ),
        migrations.AddField(
            model_name='fixedincome',
            name='KeyName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主键名称'),
        ),
        migrations.AddField(
            model_name='fixedincomecashflow',
            name='KeyName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主键名称'),
        ),
        migrations.AddField(
            model_name='intresttype',
            name='KeyName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主键名称'),
        ),
        migrations.AddField(
            model_name='investtype',
            name='KeyName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主键名称'),
        ),
    ]
