# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0034_auto_20161101_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KeyName', models.CharField(blank=True, max_length=50, null=True, verbose_name='主键名称')),
                ('Amount', models.FloatField(blank=True, default=0, null=True, verbose_name='市值')),
                ('AvgPrice', models.FloatField(blank=True, default=0, null=True, verbose_name='均价')),
                ('Quantity', models.FloatField(blank=True, default=0, null=True, verbose_name='持仓数量')),
                ('UpdateDate', models.DateField(null=True, verbose_name='更新日期')),
                ('Comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='说明')),
                ('Equity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.Equity', verbose_name='权益类信息')),
                ('InvestType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.InvestType', verbose_name='投资类别')),
            ],
            options={
                'verbose_name': '权益类持仓',
                'ordering': ['InvestType', 'Equity'],
                'verbose_name_plural': '权益类持仓',
            },
        ),
        migrations.RemoveField(
            model_name='equityreg',
            name='Equity',
        ),
        migrations.RemoveField(
            model_name='equityreg',
            name='InvestType',
        ),
        migrations.AddField(
            model_name='equityreg',
            name='EquityPosition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.EquityPosition', verbose_name='权益类持仓'),
        ),
    ]
