# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 01:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0035_auto_20161101_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equityposition',
            name='Amount',
        ),
        migrations.AlterField(
            model_name='equityposition',
            name='UpdateDate',
            field=models.DateField(default=datetime.date(1900, 1, 1), null=True, verbose_name='更新日期'),
        ),
    ]
