# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0036_auto_20161104_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityPositionStatu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquityPositionSaved', models.BooleanField(default=False, verbose_name='已更新至权益类持仓')),
                ('EquityReg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.EquityReg', verbose_name='权益类登记')),
            ],
            options={
                'verbose_name_plural': '权益类登记状态',
                'verbose_name': '权益类登记状态',
            },
        ),
    ]
