# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0038_auto_20161104_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityRegStatu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquityRegSaved', models.BooleanField(default=False, verbose_name='已更新至权益类持仓')),
            ],
            options={
                'verbose_name_plural': '权益类登记状态',
                'verbose_name': '权益类登记状态',
            },
        ),
        migrations.RemoveField(
            model_name='equitypositionstatu',
            name='EquityReg',
        ),
        migrations.AlterField(
            model_name='equityreg',
            name='EquityPosition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EquityReg', to='Finance.EquityPosition', verbose_name='权益类持仓'),
        ),
        migrations.DeleteModel(
            name='EquityPositionStatu',
        ),
        migrations.AddField(
            model_name='equityregstatu',
            name='EquityReg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EquityRegStatu', to='Finance.EquityReg', verbose_name='权益类登记'),
        ),
    ]
