# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0039_auto_20161106_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equityregstatu',
            old_name='EquityRegSaved',
            new_name='EquityPositionSaved',
        ),
    ]
