# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0040_auto_20161106_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityposition',
            name='Cost',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='成本'),
        ),
    ]
