# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0042_auto_20161109_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityCashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KeyName', models.CharField(blank=True, max_length=50, null=True, verbose_name='主键名称')),
                ('HappendDate', models.DateField(verbose_name='日期')),
                ('Amount', models.FloatField(blank=True, null=True, verbose_name='金额')),
                ('RelateEquityReg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.EquityReg', verbose_name='相关权益类登记')),
            ],
            options={
                'ordering': ['HappendDate'],
                'verbose_name': '权益类现金流',
                'verbose_name_plural': '权益类现金流',
            },
        ),
        migrations.AddField(
            model_name='equityregstatu',
            name='CashFlowSaved',
            field=models.BooleanField(default=False, verbose_name='已更新至权益类现金流'),
        ),
    ]
