# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0043_auto_20161109_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equityposition',
            name='UpdateDate',
        ),
        migrations.AlterField(
            model_name='equitycashflow',
            name='RelateEquityReg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EquityCashFlow', to='Finance.EquityReg', verbose_name='相关权益类登记'),
        ),
    ]
