# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0044_auto_20161110_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitycashflow',
            name='RelateEquityPosition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EquityCashFlow', to='Finance.EquityPosition', verbose_name='相关权益类持仓'),
        ),
    ]
