# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0045_equitycashflow_relateequityposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedIncomeStatu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CashFlowSaved', models.BooleanField(default=False, verbose_name='已更新至固定收益类现金流')),
                ('FixedIncome', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FixedIncome', to='Finance.FixedIncome', verbose_name='固定收益类')),
            ],
            options={
                'verbose_name': '固定收益类登记状态',
                'verbose_name_plural': '固定收益类登记状态',
            },
        ),
        migrations.AlterField(
            model_name='fixedincomecashflow',
            name='RelateFixedIncome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FixedIncomeCashFlow', to='Finance.FixedIncome', verbose_name='相关固定收益类'),
        ),
    ]
