# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0046_auto_20161111_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedincomestatu',
            name='FixedIncome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FixedIncomeStatu', to='Finance.FixedIncome', verbose_name='固定收益类'),
        ),
    ]
