# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0047_auto_20161111_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KeyName', models.CharField(blank=True, max_length=50, null=True, verbose_name='主键名称')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
                ('Comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='说明')),
                ('genTime', models.DateTimeField(null=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name_plural': '主报表',
                'ordering': ['genTime'],
                'verbose_name': '主报表',
            },
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KeyName', models.CharField(blank=True, max_length=50, null=True, verbose_name='主键名称')),
                ('CurSpend', models.FloatField(blank=True, default=0, null=True, verbose_name='当前投入')),
                ('CurNetValue', models.FloatField(blank=True, default=0, null=True, verbose_name='当前净值')),
                ('CurReturn', models.FloatField(blank=True, default=0, null=True, verbose_name='当前收益')),
                ('CurReturnRate', models.FloatField(blank=True, default=0, null=True, verbose_name='当前收益率')),
                ('FinSpend', models.FloatField(blank=True, default=0, null=True, verbose_name='已完成投入')),
                ('FinReturn', models.FloatField(blank=True, default=0, null=True, verbose_name='已完成收益')),
                ('FinReturnRate', models.FloatField(blank=True, default=0, null=True, verbose_name='当前收益率')),
                ('AllSpend', models.FloatField(blank=True, default=0, null=True, verbose_name='总投入')),
                ('AllReturn', models.FloatField(blank=True, default=0, null=True, verbose_name='总收益')),
                ('AllReturnRate', models.FloatField(blank=True, default=0, null=True, verbose_name='总收益率')),
                ('AnnualRate', models.FloatField(blank=True, default=0, null=True, verbose_name='年化率')),
                ('RiskHigh', models.FloatField(blank=True, default=0, null=True, verbose_name='高风险')),
                ('RiskMiddle', models.FloatField(blank=True, default=0, null=True, verbose_name='中风险')),
                ('RiskLow', models.FloatField(blank=True, default=0, null=True, verbose_name='低风险')),
                ('LiquidityHigh', models.FloatField(blank=True, default=0, null=True, verbose_name='高流动')),
                ('LiquidityMiddel', models.FloatField(blank=True, default=0, null=True, verbose_name='中流动')),
                ('LiquidityLow', models.FloatField(blank=True, default=0, null=True, verbose_name='低流动')),
            ],
            options={
                'verbose_name_plural': '报表项',
                'ordering': ['InvestType'],
                'verbose_name': '报表项',
            },
        ),
        migrations.CreateModel(
            name='subReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KeyName', models.CharField(blank=True, max_length=50, null=True, verbose_name='主键名称')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
                ('Comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name_plural': '子报表',
                'ordering': ['Name'],
                'verbose_name': '子报表',
            },
        ),
        migrations.AddField(
            model_name='investtype',
            name='IncomeType',
            field=models.CharField(blank=True, choices=[('1', '固定收益类'), ('2', '权益类')], max_length=1, null=True, verbose_name='收益类型'),
        ),
        migrations.AddField(
            model_name='reportitem',
            name='InvestType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportItem', to='Finance.InvestType', verbose_name='投资类型'),
        ),
    ]
