# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0048_auto_20161117_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportitem',
            name='SubReport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportItem', to='Finance.SubReport', verbose_name='子报表'),
        ),
        migrations.AddField(
            model_name='subreport',
            name='Report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubReport', to='Finance.Report', verbose_name='主报表'),
        ),
    ]
